export const GameConstant = Object.freeze({
    GAME_WIDTH: 720,
    GAME_HEIGHT: 1280,
  
    ENEMY_SPEED: 2,
    DEBUG_DRAW_COLLIDER: false,
    ENEMY_POOL: 10,
    
    PLAYER_VELOCITY_X: 6,
    PLAYER_VELOCITY_Y: 1,
    PLAYER_JUMP_FORCE: -20 ,
    PLAYER_GRAVITY: 0.3,
    PLAYER_VY_MAX: -10,
    PLAYER_VX_MAX: 12,
    PLAYER_ROTAE: 0.5,

    SCORE_STEP: 1,
    TOTALSPIKE: 9,
    WIDTHRECT_POINT: 450,
    HEIGHTRECT_POINT: 150,

  });