export const GameConstant = Object.freeze({
    GAME_WIDTH: 720,
    GAME_HEIGHT: 1280,
  
    WITHDBASE_GAMELOST: 500,
    HEIGHTBASE_GAMELOST: 500,
    SQUARE_SPACE : 50,
    TETROMIO_SPACE : 50,
    TWEEN_DURATION: 400
  });